[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
klave_anchor = "4Z2GnoUJwG97f6Rhee3RcH1REsY2hKiaAzs7izrbC3nz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
